apiVersion: batch/v1
kind: CronJob
metadata:
  name: btc-price-fetcher
spec:
  schedule: "0 22 * * 5" # This cron schedule is for 22:00 on Friday, adjust as per market close time
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: btc-price-fetcher
            image: btcpredictioncontainerregistry.azurecr.io/your_image:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure